### PR TITLE
adds tidybayes support

### LINKED ISSUE #50: Make it work with tidybayes package
Implement the following functions for the `stanemax` S3 class object as described in https://mjskay.github.io/tidybayes/reference/tidybayes-models.html#extending-tidybayes-1

- rstantools::posterior_epred(), rstantools::posterior_predict(), and rstantools::posterior_linpred()

### PR DESCRIPTION
**Pull request by djnavarro**
This PR provides support for tidybayes functionality. 

It extends the S3  `rstantools::posterior_predict()` methods that already exist for stanemax and stanemaxbin objects, such that methods for `rstantools::posterior_epred()`, and `rstantools::posterior_linpred()` are also exported.

Main changes:

- New S3 methods as listed above
- Refactoring of the `posterior_predict()` methods, allowing all of the `posterior_XXX()` methods to use the shared internal API provided by `pp_wrapper()`, `pp_calc()`, `pp_model_frame()` and `pp_tidy()`
- Existing unit tests for `posterior_predict()` are mirrored with similar tests for `posterior_linpred()` and `posterior_epred()`

Additional details in comments below

closes #50

### CODE REVIEW

**Comment by djnavarro** [comment]
Possible issues to consider:

- As currently implemented `posterior_predict()`, `posterior_epred()`, and `posterior_linpred()` all use roughly the same API. They all have a `returnType` argument, for instance which defaults to matrix output in order to be consistent with the expectations of rstantools, tidybayes, etc. That makes sense to me, but there is some strangeness to the fact that if you set `returnType = "dataframe"`, you'd end up with the same result regardless of which `posterior_xxx()` function you're calling (because all three produce `.prediction`, `.epred`, and `.linpred` columns). I don't know if that's what we want? Perhaps worth talking about?

- Is it worth including tests analogous to the examples in the previous comment within the unit tests? In one sense we don't need to since we're really only exporting the rstantools methods, but to the extent that users are likely to rely on tidybayes specifically, it might be worth having "upstream" tests to detect potential issues that might happen in that use case?

- I don't love the naming scheme I used for the internal functions `pp_wrapper()`, `pp_tidy()` etc are all named by analogy to the `pp_calc()` function we already have, but they aren't the most descriptive names. Perhaps we can do better than that?

As always, any other comments would be appreciated! Let me know what you think 😄

**Comment by yoshidk6** [comment]
Thank you so much for yet again very thoughtful extention for allowing tidybayes integration!!
See my comments below:

### posterior_* API

Reflecting on your comment, my preference now is to only keep returnType argument for `posterior_predict()` for backward compatibility, but flag it as deprecated in the documentation.
Instead, how about we show how to use `tidybayes::add_*_draws()` in the @examples section to help the user to transition? We can add tidybayes to Suggest in DESCRIPTION.

Along those lines, maybe we can do the same for `extract_param()`, i.e. deprecating the function and add @examples on the use of `tidybayes::spread_draws()`? The output doesn't have to be exactly the same, as long as we can get a long format data frame (long with respect to covariates).

### Test

It makes perfect sense to add tests on `tidybayes::spread_draws()` and `tidybayes::add_*_draws()` functions! It should work as long as we have tidybayes in DESCRIPTION?

### Function names

How about using the followings?

- pp_wrapper() -> .posterior_predict() ("." indicates that it's an internal wrapper function)
- pp_tidy() -> pp_update_cov_levels()

**Comment by djnavarro** [comment]
This sounds like a good plan. I should have time tomorrow/Wednesday to update the PR

**Comment by djnavarro** [comment]
Another update 🙂 

- `returnType` is now supported only for the `posterior_predict()` methods, and added deprecation warnings via `lifecycle::deprecate_warn()`
- some modest testing of the tidybayes integration has been added, and the package now takes a dependency on tidybayes, both for the tests but also in anticipation of the fact that it will likely be more central to the updated workflow
- minor internal refactoring around the newly-renamed `.posterior_predict()` function
- `pp_tidy()` renamed to `pp_update_cov_levels()`

The one thing I haven't done yet is update the examples. I was thinking it might make sense to do that via a new PR that does a wider overhaul of the examples and vignette(s) to emphasise the new workflow, and deprecate `extract_param()` at the same time?

**Comment by yoshidk6** [comment]
Thank you, they look awesome!!

- transform argument appears not passed to pp_calc
- posterior_predict_quantile (and therefore plot.stanemax and plot.stanemaxbin) results in warning, maybe we can use .posterior_predict directly inside posterior_predict_quantile. We **can** consider replacing them with posterior_epred etc,  but not sure if it’s worth the effort
- Agree with separate PR for documentation. From my quick look through, there aren’t much @examples that involves posterior_* functions, so mostly it will be updates to the vignette? Anyway I’d prioritize this one than the previous one

**Comment by djnavarro** [comment]
Fixed both issues:

- transform argument is now passed to `pp_calc()`
- `posterior_predict_quantile()` now calls the internal `.posterior_predict()` function to bypass the deprecation warning. Agreed that it might need a more substantial refactor later on, but also agreed that it can wait until later

Regarding the documentation PR, agreed that it would mostly be focused on the vignette. The idea I had in my head was to start by rewriting the vignette to emphasise the new workflow, and then update the examples so that they're aligned with the examples that appear in the rewritten vignette

**Review by yoshidk6 — APPROVED** [review]

**Comment by yoshidk6** [comment]
Perfect, thank you very much!! Agree with your point around documentation

**Pull request merged**
